server:
  port: 8080

spring:
  application:
    name: inventory-management

  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:inventorydb
    driverClassName: org.h2.Driver
    username: sa
    password:

  # JPA/Hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console

  # OAuth2 Configuration
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23li3wuAm2t1yCiw5I
            client-secret: c7847175b2c665b9312e92c5ee841833594931a0
            scope:
              - read:user
              - user:email

# Logging
logging:
  level:
    com.inventory.management: DEBUG
    org.springframework.web: INFO
    org.springframework.security: DEBUG
